# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chilldog/C++/OpenGL/lighting

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chilldog/C++/OpenGL/lighting

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/chilldog/C++/OpenGL/lighting && $(CMAKE_COMMAND) -E cmake_progress_start /home/chilldog/C++/OpenGL/lighting/CMakeFiles /home/chilldog/C++/OpenGL/lighting/chill_engine//CMakeFiles/progress.marks
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chilldog/C++/OpenGL/lighting/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/chilldog/C++/OpenGL/lighting && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
chill_engine/CMakeFiles/glad.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/glad.dir/rule
.PHONY : chill_engine/CMakeFiles/glad.dir/rule

# Convenience name for target.
glad: chill_engine/CMakeFiles/glad.dir/rule
.PHONY : glad

# fast build rule for target.
glad/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/glad.dir/build.make chill_engine/CMakeFiles/glad.dir/build
.PHONY : glad/fast

# Convenience name for target.
chill_engine/CMakeFiles/game.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/game.dir/rule
.PHONY : chill_engine/CMakeFiles/game.dir/rule

# Convenience name for target.
game: chill_engine/CMakeFiles/game.dir/rule
.PHONY : game

# fast build rule for target.
game/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/game.dir/build.make chill_engine/CMakeFiles/game.dir/build
.PHONY : game/fast

# Convenience name for target.
chill_engine/CMakeFiles/assert.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/assert.dir/rule
.PHONY : chill_engine/CMakeFiles/assert.dir/rule

# Convenience name for target.
assert: chill_engine/CMakeFiles/assert.dir/rule
.PHONY : assert

# fast build rule for target.
assert/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/assert.dir/build.make chill_engine/CMakeFiles/assert.dir/build
.PHONY : assert/fast

# Convenience name for target.
chill_engine/CMakeFiles/camera.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/camera.dir/rule
.PHONY : chill_engine/CMakeFiles/camera.dir/rule

# Convenience name for target.
camera: chill_engine/CMakeFiles/camera.dir/rule
.PHONY : camera

# fast build rule for target.
camera/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/camera.dir/build.make chill_engine/CMakeFiles/camera.dir/build
.PHONY : camera/fast

# Convenience name for target.
chill_engine/CMakeFiles/window.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/window.dir/rule
.PHONY : chill_engine/CMakeFiles/window.dir/rule

# Convenience name for target.
window: chill_engine/CMakeFiles/window.dir/rule
.PHONY : window

# fast build rule for target.
window/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/window.dir/build.make chill_engine/CMakeFiles/window.dir/build
.PHONY : window/fast

# Convenience name for target.
chill_engine/CMakeFiles/shaders.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/shaders.dir/rule
.PHONY : chill_engine/CMakeFiles/shaders.dir/rule

# Convenience name for target.
shaders: chill_engine/CMakeFiles/shaders.dir/rule
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/shaders.dir/build.make chill_engine/CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

# Convenience name for target.
chill_engine/CMakeFiles/figures.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/figures.dir/rule
.PHONY : chill_engine/CMakeFiles/figures.dir/rule

# Convenience name for target.
figures: chill_engine/CMakeFiles/figures.dir/rule
.PHONY : figures

# fast build rule for target.
figures/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/figures.dir/build.make chill_engine/CMakeFiles/figures.dir/build
.PHONY : figures/fast

# Convenience name for target.
chill_engine/CMakeFiles/buffer_obj.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/buffer_obj.dir/rule
.PHONY : chill_engine/CMakeFiles/buffer_obj.dir/rule

# Convenience name for target.
buffer_obj: chill_engine/CMakeFiles/buffer_obj.dir/rule
.PHONY : buffer_obj

# fast build rule for target.
buffer_obj/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/buffer_obj.dir/build.make chill_engine/CMakeFiles/buffer_obj.dir/build
.PHONY : buffer_obj/fast

# Convenience name for target.
chill_engine/CMakeFiles/light.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/light.dir/rule
.PHONY : chill_engine/CMakeFiles/light.dir/rule

# Convenience name for target.
light: chill_engine/CMakeFiles/light.dir/rule
.PHONY : light

# fast build rule for target.
light/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/light.dir/build.make chill_engine/CMakeFiles/light.dir/build
.PHONY : light/fast

# Convenience name for target.
chill_engine/CMakeFiles/imgui.dir/rule:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chill_engine/CMakeFiles/imgui.dir/rule
.PHONY : chill_engine/CMakeFiles/imgui.dir/rule

# Convenience name for target.
imgui: chill_engine/CMakeFiles/imgui.dir/rule
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

include/imgui/backend/imgui_impl_glfw.o: include/imgui/backend/imgui_impl_glfw.cpp.o
.PHONY : include/imgui/backend/imgui_impl_glfw.o

# target to build an object file
include/imgui/backend/imgui_impl_glfw.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/backend/imgui_impl_glfw.cpp.o
.PHONY : include/imgui/backend/imgui_impl_glfw.cpp.o

include/imgui/backend/imgui_impl_glfw.i: include/imgui/backend/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/backend/imgui_impl_glfw.i

# target to preprocess a source file
include/imgui/backend/imgui_impl_glfw.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/backend/imgui_impl_glfw.cpp.i
.PHONY : include/imgui/backend/imgui_impl_glfw.cpp.i

include/imgui/backend/imgui_impl_glfw.s: include/imgui/backend/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/backend/imgui_impl_glfw.s

# target to generate assembly for a file
include/imgui/backend/imgui_impl_glfw.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/backend/imgui_impl_glfw.cpp.s
.PHONY : include/imgui/backend/imgui_impl_glfw.cpp.s

include/imgui/backend/imgui_impl_opengl3.o: include/imgui/backend/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/backend/imgui_impl_opengl3.o

# target to build an object file
include/imgui/backend/imgui_impl_opengl3.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/backend/imgui_impl_opengl3.cpp.o
.PHONY : include/imgui/backend/imgui_impl_opengl3.cpp.o

include/imgui/backend/imgui_impl_opengl3.i: include/imgui/backend/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backend/imgui_impl_opengl3.i

# target to preprocess a source file
include/imgui/backend/imgui_impl_opengl3.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/backend/imgui_impl_opengl3.cpp.i
.PHONY : include/imgui/backend/imgui_impl_opengl3.cpp.i

include/imgui/backend/imgui_impl_opengl3.s: include/imgui/backend/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backend/imgui_impl_opengl3.s

# target to generate assembly for a file
include/imgui/backend/imgui_impl_opengl3.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/backend/imgui_impl_opengl3.cpp.s
.PHONY : include/imgui/backend/imgui_impl_opengl3.cpp.s

include/imgui/imgui.o: include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.o: include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.o

# target to build an object file
include/imgui/imgui_demo.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.cpp.o

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_tables.o: include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.o

# target to build an object file
include/imgui/imgui_tables.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.cpp.o

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/imgui.dir/build.make chill_engine/CMakeFiles/imgui.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

src/assert.o: src/assert.cpp.o
.PHONY : src/assert.o

# target to build an object file
src/assert.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/assert.dir/build.make chill_engine/CMakeFiles/assert.dir/src/assert.cpp.o
.PHONY : src/assert.cpp.o

src/assert.i: src/assert.cpp.i
.PHONY : src/assert.i

# target to preprocess a source file
src/assert.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/assert.dir/build.make chill_engine/CMakeFiles/assert.dir/src/assert.cpp.i
.PHONY : src/assert.cpp.i

src/assert.s: src/assert.cpp.s
.PHONY : src/assert.s

# target to generate assembly for a file
src/assert.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/assert.dir/build.make chill_engine/CMakeFiles/assert.dir/src/assert.cpp.s
.PHONY : src/assert.cpp.s

src/buffer_obj.o: src/buffer_obj.cpp.o
.PHONY : src/buffer_obj.o

# target to build an object file
src/buffer_obj.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/buffer_obj.dir/build.make chill_engine/CMakeFiles/buffer_obj.dir/src/buffer_obj.cpp.o
.PHONY : src/buffer_obj.cpp.o

src/buffer_obj.i: src/buffer_obj.cpp.i
.PHONY : src/buffer_obj.i

# target to preprocess a source file
src/buffer_obj.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/buffer_obj.dir/build.make chill_engine/CMakeFiles/buffer_obj.dir/src/buffer_obj.cpp.i
.PHONY : src/buffer_obj.cpp.i

src/buffer_obj.s: src/buffer_obj.cpp.s
.PHONY : src/buffer_obj.s

# target to generate assembly for a file
src/buffer_obj.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/buffer_obj.dir/build.make chill_engine/CMakeFiles/buffer_obj.dir/src/buffer_obj.cpp.s
.PHONY : src/buffer_obj.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/camera.dir/build.make chill_engine/CMakeFiles/camera.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/camera.dir/build.make chill_engine/CMakeFiles/camera.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/camera.dir/build.make chill_engine/CMakeFiles/camera.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/figures.o: src/figures.cpp.o
.PHONY : src/figures.o

# target to build an object file
src/figures.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/figures.dir/build.make chill_engine/CMakeFiles/figures.dir/src/figures.cpp.o
.PHONY : src/figures.cpp.o

src/figures.i: src/figures.cpp.i
.PHONY : src/figures.i

# target to preprocess a source file
src/figures.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/figures.dir/build.make chill_engine/CMakeFiles/figures.dir/src/figures.cpp.i
.PHONY : src/figures.cpp.i

src/figures.s: src/figures.cpp.s
.PHONY : src/figures.s

# target to generate assembly for a file
src/figures.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/figures.dir/build.make chill_engine/CMakeFiles/figures.dir/src/figures.cpp.s
.PHONY : src/figures.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/game.dir/build.make chill_engine/CMakeFiles/game.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/game.dir/build.make chill_engine/CMakeFiles/game.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/game.dir/build.make chill_engine/CMakeFiles/game.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/glad.dir/build.make chill_engine/CMakeFiles/glad.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/glad.dir/build.make chill_engine/CMakeFiles/glad.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/glad.dir/build.make chill_engine/CMakeFiles/glad.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/light.o: src/light.cpp.o
.PHONY : src/light.o

# target to build an object file
src/light.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/light.dir/build.make chill_engine/CMakeFiles/light.dir/src/light.cpp.o
.PHONY : src/light.cpp.o

src/light.i: src/light.cpp.i
.PHONY : src/light.i

# target to preprocess a source file
src/light.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/light.dir/build.make chill_engine/CMakeFiles/light.dir/src/light.cpp.i
.PHONY : src/light.cpp.i

src/light.s: src/light.cpp.s
.PHONY : src/light.s

# target to generate assembly for a file
src/light.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/light.dir/build.make chill_engine/CMakeFiles/light.dir/src/light.cpp.s
.PHONY : src/light.cpp.s

src/shaders.o: src/shaders.cpp.o
.PHONY : src/shaders.o

# target to build an object file
src/shaders.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/shaders.dir/build.make chill_engine/CMakeFiles/shaders.dir/src/shaders.cpp.o
.PHONY : src/shaders.cpp.o

src/shaders.i: src/shaders.cpp.i
.PHONY : src/shaders.i

# target to preprocess a source file
src/shaders.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/shaders.dir/build.make chill_engine/CMakeFiles/shaders.dir/src/shaders.cpp.i
.PHONY : src/shaders.cpp.i

src/shaders.s: src/shaders.cpp.s
.PHONY : src/shaders.s

# target to generate assembly for a file
src/shaders.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/shaders.dir/build.make chill_engine/CMakeFiles/shaders.dir/src/shaders.cpp.s
.PHONY : src/shaders.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/window.dir/build.make chill_engine/CMakeFiles/window.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/window.dir/build.make chill_engine/CMakeFiles/window.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	cd /home/chilldog/C++/OpenGL/lighting && $(MAKE) $(MAKESILENT) -f chill_engine/CMakeFiles/window.dir/build.make chill_engine/CMakeFiles/window.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... assert"
	@echo "... buffer_obj"
	@echo "... camera"
	@echo "... figures"
	@echo "... game"
	@echo "... glad"
	@echo "... imgui"
	@echo "... light"
	@echo "... shaders"
	@echo "... window"
	@echo "... include/imgui/backend/imgui_impl_glfw.o"
	@echo "... include/imgui/backend/imgui_impl_glfw.i"
	@echo "... include/imgui/backend/imgui_impl_glfw.s"
	@echo "... include/imgui/backend/imgui_impl_opengl3.o"
	@echo "... include/imgui/backend/imgui_impl_opengl3.i"
	@echo "... include/imgui/backend/imgui_impl_opengl3.s"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.o"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_tables.o"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... src/assert.o"
	@echo "... src/assert.i"
	@echo "... src/assert.s"
	@echo "... src/buffer_obj.o"
	@echo "... src/buffer_obj.i"
	@echo "... src/buffer_obj.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/figures.o"
	@echo "... src/figures.i"
	@echo "... src/figures.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/light.o"
	@echo "... src/light.i"
	@echo "... src/light.s"
	@echo "... src/shaders.o"
	@echo "... src/shaders.i"
	@echo "... src/shaders.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/chilldog/C++/OpenGL/lighting && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

